title: Vintalie – Soluções Digitais
description: Ideias que movem marcas.
baseurl: ""
url: "https://vintalie.com.br"

collections:
  testimonials:
    output: true
    permalink: /depoimentos/:path/

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "testimonials"
    values:
      layout: "testimonial"
  - scope:
      path: ""
    values:
      layout: "default"

# Defaults para páginas de categoria
defaults:
  - scope:
      path: "categories/*.md"
    values:
      layout: "category"

# Configurações de paginação
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title_suffix: ' - página :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
plugins:
  - jekyll-paginate-v2
